### ISSUE TITLE
Setup Database

### ISSUE THREAD

**Issue by dpfurners** [dpfurners/Battleship#1]
There should be a Database Interface thats creates an database connection on initialization. 
For now create a User Table and create a function to get information when the client loggs in to the server. 
Make sure to add a new user when the user is not registered already. 

The class should be created in [here](https://github.com/dpfurners/Battleship/blob/sprint-0/server/database.py).

**Comment by Salminga** [comment]
I had no problems completing this issue, I had fun coding this and I learned a lot about databases.
It took me about 3 hours to set up the database and make the functions for log in, sign in & add a win to a specific account.
