### ISSUE TITLE
Server Setup

### ISSUE THREAD

**Issue by dpfurners** [dpfurners/Battleship#5]
Create a Class to be able to connect to (Accept clients). If a client connects to the server, the client must provide login data (username, password). The server then should send the login data to the database interface and receives all the information about the user. This user data is stored along with the socket connection (to the client) in the Server Class.

The class should be created in [here](https://github.com/dpfurners/Battleship/blob/sprint-0/server/network.py).

**Comment by aleksxmrkvc** [comment]
Went pretty good, handing over the data (username, password) took some time, connect to database is missing
